### ISSUE TITLE
Dataset Not Available, Please Help

### ISSUE THREAD

**Issue by varungupta31** [Eladhi/CLID#1]
Dear author, the first step in the `README` of this repo asks to download a bunch of files from here: https://github.com/LuoweiZhou/VLP#-data-preparation

However, the download links in the mentioned repo (https://github.com/LuoweiZhou/VLP#-data-preparation) don't work anymore.

> To prepare for the pre-training, first download and uncompress our pre-processed Conceptual Captions (CC) [data(6GB)](https://onedrive.live.com/download?cid=E5364FD183A1F5BB&resid=E5364FD183A1F5BB%213781&authkey=ANA--esfJnWIKIE) and place under your data root. Then, download and uncompress the region features from Google Drive ([feat(509GB)](https://drive.google.com/file/d/14mr49-14-ZjJXOohInzoOLBZlJb_y7fh/view?usp=sharing), [cls(468GB)](https://drive.google.com/file/d/1kRlnQJcTjGFaOHSptekgG98MiCsTQYDt/view?usp=sharing)) under the CC/region_feat_gvd_wo_bgd/feat_cls_1000_float16 dir. To evaluate CC on caption generation, download the reference [file](https://onedrive.live.com/download?cid=E5364FD183A1F5BB&resid=E5364FD183A1F5BB%212017&authkey=AHy5eiJM75RwPxg) and place it under coco-caption/annotations.

Can you please help provide the features so I can download them?

Without these (the first step), it is tricky to run anything in this repo.
Thanks

@Eladhi

**Comment by varungupta31** [comment]
Given that your work is most recent, and seeing the last response to issues on the quoted repo was few years back, I don't hope much for a response from their end.

**Comment by Eladhi** [comment]
Hi,
You don't need their data of CC. The link of COCO still works for me.
Anyway, I added the script others/[extract_FRCNN_feats.py](https://github.com/Eladhi/CLID/blob/master/others/extract_FRCNN_feats.py) which I once used to extract features for another dataset. Just add it to this base repo [code](https://gitlab.com/meetshah1995/vqa-maskrcnn-benchmark). Maybe small modifications are required, but as I recall it ran smoothly as is.

**Comment by varungupta31** [comment]
Appreciate the help, and we modified the script for feature extraction.
Thanks again.
